// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlvLrOdNgqKsIRgMjQXB6q38pSK-00Kns',
    appId: '1:724715851372:web:61c1ee5438dd9ee43e1249',
    messagingSenderId: '724715851372',
    projectId: 'hamzaepi',
    authDomain: 'hamzaepi.firebaseapp.com',
    storageBucket: 'hamzaepi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi6dbFKJQj8ggHoK89HEFuveXoazPQBqo',
    appId: '1:724715851372:android:4995ab08b12a939b3e1249',
    messagingSenderId: '724715851372',
    projectId: 'hamzaepi',
    storageBucket: 'hamzaepi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfh0_2qS9Busc4LIwhavLkbT7OSNN2p7Y',
    appId: '1:724715851372:ios:1187c4ec039101ce3e1249',
    messagingSenderId: '724715851372',
    projectId: 'hamzaepi',
    storageBucket: 'hamzaepi.firebasestorage.app',
    iosBundleId: 'com.epi.etudiant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfh0_2qS9Busc4LIwhavLkbT7OSNN2p7Y',
    appId: '1:724715851372:ios:1187c4ec039101ce3e1249',
    messagingSenderId: '724715851372',
    projectId: 'hamzaepi',
    storageBucket: 'hamzaepi.firebasestorage.app',
    iosBundleId: 'com.epi.etudiant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlvLrOdNgqKsIRgMjQXB6q38pSK-00Kns',
    appId: '1:724715851372:web:b4caff699decbc483e1249',
    messagingSenderId: '724715851372',
    projectId: 'hamzaepi',
    authDomain: 'hamzaepi.firebaseapp.com',
    storageBucket: 'hamzaepi.firebasestorage.app',
  );
}
